name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - rich-text-implementation
  workflow_dispatch:

# આ લાઈન પરમિશન એરર દૂર કરશે
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # અહી 'stable' ની જગ્યાએ 'master' કર્યું છે કારણ કે 3.38.2 હજુ સ્ટેબલ નથી
          channel: 'master'
          # એરર મેસેજ મુજબ નવું વર્ઝન સેટ કર્યું છે
          flutter-version: '3.38.2'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Web App
        # આ કમાન્ડથી build/web ફોલ્ડર બનશે
        run: flutter build web --release --base-href "/my-game/"

      # --- સૌથી મહત્વનું સ્ટેપ (આનાથી જ સાઈટ દેખાશે) ---
      - name: Fix for GitHub Pages (Disable Jekyll)
        run: |
          cd build/web
          touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true # આ જૂની કેશ ક્લીન કરીને નવું પેજ બનાવશે
